dependencies:
- name: elasticsearch
  version: ^1.10.0
  repository: http://127.0.0.1:8080
- name: kibana
  version: 1.0.0
  repository: http://127.0.0.1:8080
- name: kafka
  version: ^0.13.2
  repository: http://127.0.0.1:8080
  condition: kafka.enabled
- name: logstash
  version: ^1.3.0
  repository: http://127.0.0.1:8080
#- name: nginx-ldapauth-proxy
#  version: ^0.1.0
#  repository: http://127.0.0.1:8080
#  condition: nginx-ldapauth-proxy.enabled
#- name: elasticsearch-curator
# version: ^1.0.0
#  repository: http://127.0.0.1:8080
#  condition: elasticsearch-curator.enabled
#- name: elasticsearch-exporter
#  version: ^0.4.0
#  repository: http://127.0.0.1:8080
#  condition: elasticsearch-exporter.enabled
