dependencies:
- name: elasticsearch
  version: ^1.10.0
  repository: https://github.com/akinolasupo/charts.git
- name: kibana
  version: ^0.16.0
  repository: https://github.com/akinolasupo/charts.git
- name: kafka
  version: ^0.13.2
  repository: https://github.com/akinolasupo/charts.git
  condition: kafka.enabled
- name: nginx-ldapauth-proxy
  version: ^0.1.0
  repository: https://github.com/akinolasupo/charts.git
  condition: nginx-ldapauth-proxy.enabled
- name: elasticsearch-curator
  version: ^1.0.0
  repository: https://github.com/akinolasupo/charts.git
  condition: elasticsearch-curator.enabled
- name: elasticsearch-exporter
  version: ^0.4.0
  repository: https://github.com/akinolasupo/charts.git
  condition: elasticsearch-exporter.enabled
